import React from "react";
import styled from 'styled-components';

import PageHero from '../components/PageHero.jsx';
import PageContent from '../components/PageContent.jsx';
import Footer from '../components/Footer.jsx';


const Disclaimer = () => {
  return(
    <>
      <PageHero
        title="DISCLAIMER"
       />
       <PageContent
        para1="QRazor will not memorize, store or distribute the links you submit to QRazor QR code generator for QR code generation process."
        para2="QRazor generates QR code using a built-in algorithm based on translation of user-submitted string of characters into graphical encoding readable to QR scanners."
        para3="QRazor does not keep or distribute any pre-written QR codes. All output QR codes are a result of a user-submitted string of characters translated by the built-in algorithm."
        para4='The default QR code picture visible by default, is visible until user submits own string of characters and activates the button labeled as Generate QR'
        para5="Any QR code produced by QRazor QR Code Generator and subsequently presented, shared or marketed is the result of user actions. QRazor and it's creator Sarif Design cannot be held accountable for any misuse of QR code submitted, generated and distributed by the user, nor be held accountable for any damages directly resulting from user's misuse of QRazor and QR code generated by QRazor."
        para6="All makreting ideas presented in Creative Ideas section are purely suggenstions on how to use QR code for marketing purposes. QRazor and it's creator - Sarif Design do not guarantee the finacial success resulting in users practical application of those suggenstions."
       />
      <Footer />
    </>
  );
}

export default Disclaimer;
